### PR TITLE
Add functions metadata to new functions

### PR DESCRIPTION
**Pull request by Mahjouba91**

### CODE REVIEW

**Comment by Mahjouba91** [comment]
Hi,

I fixed all bugs that I introduced before, it will be nice to have a last code review from another dev to prepare the next release.

**Comment by lesterchan** [comment]
Yea, I probably have to give it a test first before CRing it when I am free. Sorry for the delay, been really busy with my full time job.

**Comment by Mahjouba91** [comment]
Hello, no news ?

**Comment by lesterchan** [comment]
Sorry I still haven't and have no time to test it yet. It is a huge and potential breaking change, I prefer not to rush it.

**Pull request merged**
